
title: Tianye Wang
url: 'http://wtyjack.github.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: Tianye Wang
tagline: Software Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email_1: wtyjack@gmail.com
email_2: wang2074@purdue.edu
phone: 312-972-6708
website: wtyjack.github.io #do not add http://
linkedin: tianye-wang-159164a4
github: wtyjack
twitter: '@wtyjack'

